{
 "title": "Subreddit sentiments",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sentiment Score  NLTK Compound",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "columnId": "subreddit",
     "columnTime": "api_timestamp",
     "columnValue": "upvotes",
     "keyspace": "reddit",
     "table": "subreddit_sentiment_avg",
     "target": "select subreddit, CAST(sentiment_score_compound_avg AS double), ingest_timestamp from reddit.subreddit_sentiment_avg where subreddit IN ('AskReddit', 'funny', 'gaming', 'aww', 'worldnews') and ingest_timestamp>$__timeFrom and ingest_timestamp<$__timeTo ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Sentiment Score  NLTK Compound",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "select subreddit, CAST(sentiment_score_compound_avg AS double), ingest_timestamp from reddit.subreddit_sentiment_avg where subreddit IN ('india', 'usa', 'unitedkingdom', 'australia', 'russia', 'China') and ingest_timestamp>$__timeFrom and ingest_timestamp<$__timeTo;"
    }
   ]
  },
  {
   "title": "Sentiment Score TextBlob Polarity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "columnId": "subreddit",
     "columnTime": "api_timestamp",
     "columnValue": "upvotes",
     "keyspace": "reddit",
     "table": "subreddit_sentiment_avg",
     "target": "select subreddit, CAST(sentiment_score_polarity_avg AS double), ingest_timestamp from reddit.subreddit_sentiment_avg where subreddit IN ('AskReddit', 'funny', 'gaming', 'aww', 'worldnews') and ingest_timestamp>$__timeFrom and ingest_timestamp<$__timeTo ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Sentiment Score TextBlob Polarity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "columnId": "subreddit",
     "columnTime": "api_timestamp",
     "columnValue": "upvotes",
     "keyspace": "reddit",
     "table": "subreddit_sentiment_avg",
     "target": "select subreddit, CAST(sentiment_score_polarity_avg AS double), ingest_timestamp from reddit.subreddit_sentiment_avg where subreddit IN ('AskReddit', 'funny', 'gaming', 'aww', 'worldnews') and ingest_timestamp>$__timeFrom and ingest_timestamp<$__timeTo ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Sentiment Score Text Blob Subjectivity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "target": "select subreddit, CAST(sentiment_score_subjectivity_avg AS double), ingest_timestamp from reddit.subreddit_sentiment_avg where subreddit IN ('india', 'usa', 'unitedkingdom', 'australia', 'russia', 'China') and ingest_timestamp>$__timeFrom and ingest_timestamp<$__timeTo;"
    }
   ]
  },
  {
   "title": "Sentiment Score Text Blob Subjectivity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "columnId": "subreddit",
     "columnTime": "api_timestamp",
     "columnValue": "upvotes",
     "keyspace": "reddit",
     "table": "subreddit_sentiment_avg",
     "target": "select subreddit, CAST(sentiment_score_subjectivity_avg AS double), ingest_timestamp from reddit.subreddit_sentiment_avg where subreddit IN ('AskReddit', 'funny', 'gaming', 'aww', 'worldnews') and ingest_timestamp>$__timeFrom and ingest_timestamp<$__timeTo ALLOW FILTERING;"
    }
   ]
  }
 ]
}